sequenceDiagram
    participant browser
    participant server

    Note over browser: User writes a note and clicks the Save button

    Note over browser: The JS code intercepts the form submission,<br/>adds the new note to the local list,<br/>and rerenders the note list on the page.

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    Note right of browser: The payload is a JSON object: <br/> { "content": "SPA is seamless", "date": "2026-02-10" }
    server-->>browser: 201 Created
    deactivate server

    Note over browser: No page reload or further GET requests occur.